jwt:
  secret: 9dshcjdcjdjndjncjdncd9vdcskvkdncsmmskcmkvmdmfmvdksnanwajkuvidvhjdh3jdssxs
  lifetime: 30m

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/online-store
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true


server:
  port:
    8080
